### ISSUE TITLE
doesnt gin support web sockets ? you used gorilla

### ISSUE THREAD

**Issue by joeblew99** [nordicdyno/ws-gnats-hub#1]
just wondering

**Comment by nordicdyno** [comment]
I've made research today, and I sure Gin doesn't support websockets "out of the box".
https://godoc.org/github.com/gin-gonic/gin?imports
https://github.com/gin-gonic/gin/issues/461

Anyway I was more familiar with gorilla's sockets implementation at the moment when I wrote this code.
Now I prefer "golang.org/x/net/websocket" it looks more reliable and stdlib friendly.

**Comment by joeblew99** [comment]
I also did not know about the built in version.
Right one :)
